[dataset]
name = "rl-task-samples"
description = "A curated sample of historical EVM exploit-reproduction environments"
authors = ["Ivan Bogatyy"]
keywords = ["smart-contracts", "security", "reinforcement-learning", "foundry"]

[[tasks]]
name = "rl-exploits/2026-07-15-notional-v1"

[[tasks]]
name = "rl-exploits/2026-07-01-edel-xstock"

[[tasks]]
name = "rl-exploits/2026-06-17-lbp"

[[tasks]]
name = "rl-exploits/2026-06-07-ambient"

[[tasks]]
name = "rl-exploits/2026-04-28-rwa-vault"

[[tasks]]
name = "rl-exploits/2025-11-03-balancer-v2"

[[tasks]]
name = "rl-exploits/2024-09-03-penpie"
